services:
  nginx:
    image: nginx:latest
    restart: always
    expose:
      - "80"
    networks:
      - nginx
    volumes:
      - ./ugc_service/src/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ugc_service/src/nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - ugc
    ports:
      - "80:80"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.2
    container_name: zookeeper
    hostname: zookeeper
    restart: always
    expose:
      - "2181"
#    volumes:
#      - ./confluent/zookeeper/data:/var/lib/zookeeper/data
    networks:
      - zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: yes

  ugc:
    build: ugc_service
    restart: always
    expose:
      - "8000"
    depends_on:
      - connect
    networks:
      - ugc
    env_file:
      - ./.env.prod

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    expose:
      - "9008"
    ports:
      - "9008:9000"
    networks:
      - kafdrop
    depends_on:
      - broker
    environment:
      - KAFKA_BROKERCONNECT=broker:29092

  broker:
    image: confluentinc/cp-kafka:7.1.2
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9192:9192"
#    volumes:
#      - ./confluent/kafka/data:/var/lib/kafka/data
    networks:
      - broker
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_ADVERTISED_HOST_NAME: broker
      ALLOW_PLAINTEXT_LISTENER: yes

  schema-registry:
    image: confluentinc/cp-schema-registry:6.0.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    networks:
      - schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  connect:
    image: cnfldemos/cp-server-connect-datagen:0.4.0-6.0.1
    hostname: connect
    container_name: connect
    depends_on:
      - broker
      - schema-registry
    networks:
      - connect
    volumes:
      - ./confluent/connect/jars:/usr/share/java/confluent_hub_components
    ports:
      - "8083:8083"
      - "9102:9102"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker:29092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
      KAFKA_JMX_PORT: 9102
      KAFKA_JMX_HOSTNAME: localhost

  clickhouse-node1:
    image: yandex/clickhouse-server:21.7.4
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    expose:
      - "8123"
      - "9000"
    networks:
      - clickhouse
    volumes:
      - ./ugc_service/src/db/clickhouse/data/node1:/etc/clickhouse-server
    depends_on:
      - zookeeper

  mongodb:
    image: mongo:4.2-rc-bionic
    hostname: mongodb
    container_name: mongodb
    networks:
      - mongodb
    depends_on:
      - broker
      - connect
    ports:
      - 27017:27017


networks:
  nginx:
    name: ugc_net
  ugc:
    name: ugc_net
  zookeeper:
    name: ugc_net
  kafdrop:
    name: ugc_net
  broker:
    name: ugc_net
  schema-registry:
    name: ugc_net
  connect:
    name: ugc_net
  clickhouse:
    name: ugc_net
  mongodb:
    name: ugc_net