@startuml
!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/cerulean-outline/puml-theme-cerulean-outline.puml
skinparam backgroundColor #F1F6F5
skinparam ArrowThickness 1

header =Кинопоиск

frame **AdminPanel** {
  [DjangoPanel]
  rectangle Nginx #Technology
  package StaticFiles
  database Postgres
  actor Менеджеры as Client

}

Client -> Nginx: Запрос на подключение
Nginx -> DjangoPanel: Подключение
DjangoPanel <-down-> Postgres
Nginx -down-> StaticFiles
StaticFiles -> Client

frame **FullTextSearch** {
  [ETL]
  database Elasticsearch
}

ETL -> Elasticsearch: Загрузка данных
Postgres --> ETL: Извлечение данных

frame **AsyncApi** {
  database RedisCluster #Implementation
  [FastapiApp]
  rectangle Nginx as Nginx2 #Technology
  actor Клиенты as Clients
}

ETL -up-> FastapiApp
FastapiApp <-up-> RedisCluster
Clients -down-> Nginx2
Nginx2 --> FastapiApp

frame **Auth** {
  database Postgres as Postgres2
  database Redis #Implementation
  [FlaskApp]
  rectangle Nginx as Nginx3 #Technology
}

FastapiApp -> Nginx3
Nginx3 --> [FlaskApp]
[FlaskApp] -down-> Postgres2
[FlaskApp] -down-> Redis

@enduml
