name: Code Sanity Check and Mypy

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r ugc_service/requirements.txt
#    - name: Build and run Docker Compose
#      run: |
#        docker-compose -f docker-compose-github.yml up --build
#
#    - name: Run sanity check
#      run: |
#        python3 -m pytest ugc_service/tests/functional/src/ --sanity-check

    - name: Run mypy
      run: |
        mypy --ignore-missing-imports ugc_service/src 

    - name: Send Telegram message on success
      if: success()
      env:
        API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
        CHAT_ID: ${{ secrets.QA_CHAT_ID }}
      run: |
        pip install python-telegram-bot
        python .github/tools/send_message.py ${API_TOKEN} ${CHAT_ID} "Code Sanity Check and Mypy passed successfully!"
