name: Code Sanity Check and Mypy

on:
  push:
    branches: [ "development-zelenov-mypy" ]
  pull_request:
    branches: [ "development-zelenov-mypy" ]

jobs:
  check:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        python-version: [ 3.7, 3.8, 3.9 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
#        with:
#          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r ugc_service/requirements.txt 

#      - name: Run sanity check
#        run: |
#          python ugc_service/src/main.py --sanity-check

      - name: Run mypy
        run: |
          mypy --ignore-missing-imports .

      - name: Send Telegram message on success
      if: success()
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        python send_telegram_message.py ${API_TOKEN} ${CHAT_ID} "CI tests passed successfully!"
