name: Mypy

on:
  push:
    branches: [ "development-zelenov-mypy" ]
  pull_request:
    branches: [ "development-zelenov-mypy" ]

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install mypy

    - name: Run Mypy
      run: |
        mypy --ignore-missing-imports .
